version: '3.7'

services:
  weaviate:
    image: semitechnologies/weaviate:latest
    environment:
      QUERY_DEFAULTS_LIMIT: 100
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "false"
      PERSISTENCE_DATA_PATH: "./data"
      DEFAULT_VECTORIZER_MODULE: "text2vec-transformers"
      ENABLE_MODULES: "text2vec-transformers"
      TRANSFORMERS_INFERENCE_API: "https://inference-api.your-transformers-service.com"
      WEAVIATE_AUTHENTICATION_ADMIN_USERNAME: ${WEAVIATE_AUTHENTICATION_ADMIN_USERNAME}
      WEAVIATE_AUTHENTICATION_ADMIN_PASSWORD: ${WEAVIATE_AUTHENTICATION_ADMIN_PASSWORD}
    ports:
      - "8080:8080"

  app:
    build:
      context: .
    depends_on:
      - weaviate
    command: ["python", "app.py"]
    ports:
      - "80:8080"
